### ISSUE TITLE
Exception has been thrown at the target of an invocation exception

### ISSUE THREAD

**Issue by Sonderwoods** [DanielAbalde/Tenrec#1]
Hi @DanielAbalde ,

Im trying to setup the unit tests here, but when i start the tests in VS, but it seems that some dlls are not copied on build. Any clue?

![image](https://github.com/DanielAbalde/Tenrec/assets/19936679/423b12fb-0754-4ca4-a294-830b140b3bb0)

This is on Rhino 7.

**Comment by Sonderwoods** [comment]
FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files\Rhino 7\System\System.Runtime.CompilerServices.Unsafe.dll' or one of its dependencies. The system cannot find the file specified.

It does however exist:
![image](https://github.com/DanielAbalde/Tenrec/assets/19936679/a1d31154-1aa2-400d-9662-4d98e9042dd7)

**Comment by Sonderwoods** [comment]
Changed System and System.Core  Copy local -> True.

Now I'm getting a similar but different exception:  

`
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\Rhino 7\System\System.Runtime.CompilerServices.Unsafe.dll' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`

**Comment by Sonderwoods** [comment]
Maybe not entirely related to Tenrec, but I'll keep the post here for archive.

I had to remove the below from my app.config (inside of my Unittest project)

![image](https://github.com/DanielAbalde/Tenrec/assets/19936679/92f8dbf6-b049-4383-b8d8-9314fa8f0d77)

**Comment by DanielAbalde** [comment]
Hi @Sonderwoods, sorry I was on a trip. Thank you for reporting the bug and the fix.
